name: Build Wiki Container
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      name:
        required: true
        type: string

env:
  IMAGE_NAME: '${{ inputs.image }}'
  CONTAINER_NAME: 'wiki-${{ inputs.name }}'


jobs:
  deploy:
    runs-on:
      - self-hosted
      - docker-knm-dev1
    env:
      OLD_CONTAINER_NAME: wiki-{{ inputs.name }}-${{ github.run_number }}
    steps:
      - run: docker stop $CONTAINER_NAME
        id: container_stop
        continue-on-error: true
      - run: docker rename wiki-knm-alm $OLD_CONTAINER_NAME
        if: ${{ steps.container_stop.outcome == 'success' }}
      - name: Start Container
        run: >
          docker run
          --name wiki-knm-alm
          --detach
          --network=traefik
          --label 'traefik.enable=true'
          --label 'traefik.docker.network=traefik'
          --label 'traefik.http.routers.$CONTAINER_NAME.rule=Host(`wiki.knm.io`) && PathPrefix(`/${{ inputs.name }}`)'
          --label 'traefik.http.routers.$CONTAINER_NAME.middlewares=redirect@file'
          --label 'traefik.http.services.$CONTAINER_NAME.loadbalancer.server.port=80'
          $IMAGE_NAME
      - name: Rollback
        if: ${{ failure() }}
        run: >
         docker rename $OLD_CONTAINER_NAME $CONTAINER_NAME;
         docker start $CONTAINER_NAME
